# Generated by Django 6.0.5 on 2026-05-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrasena',
            fields=[
                ('id_contrasena', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=80)),
                ('hash_contrasena', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contrasena',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_Documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=22)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema_usuario.documento')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id_historial_acceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_intento', models.DateTimeField()),
                ('exitoso', models.BooleanField(default=True)),
                ('ip_origen', models.CharField(max_length=20)),
                ('fallo_motivo', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('contrasena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema_usuario.contrasena')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema_usuario.usuario')),
            ],
            options={
                'db_table': 'historial_acceso',
            },
        ),
        migrations.AddField(
            model_name='contrasena',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema_usuario.usuario'),
        ),
    ]
