# Generated by Django 6.0.5 on 2026-05-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='encuentro',
            fields=[
                ('id_encuentro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_torneo', models.IntegerField()),
                ('id_tipo_distribucion', models.IntegerField()),
                ('fase_torneo', models.CharField(choices=[('Grupos', 'Grupos'), ('Octavos', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semifinal', 'Semifinal'), ('Final', 'Final')], max_length=20)),
                ('id_equipo_1', models.IntegerField()),
                ('resultado_equipo_1', models.CharField(choices=[('Ganador', 'Ganador'), ('Perdedor', 'Perdedor'), ('Empate', 'Empate')], max_length=20)),
                ('id_equipo_2', models.IntegerField()),
                ('resultado_equipo_2', models.CharField(choices=[('Ganador', 'Ganador'), ('Perdedor', 'Perdedor'), ('Empate', 'Empate')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'encuentro',
            },
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='grupo_encuentro',
            fields=[
                ('id_grupo_encuentro', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_encuentro', models.ForeignKey(db_column='id_encuentro', on_delete=django.db.models.deletion.CASCADE, to='gestion_encuentro.encuentro')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='gestion_encuentro.grupo')),
            ],
            options={
                'db_table': 'grupo_encuentro',
            },
        ),
        migrations.CreateModel(
            name='grupo_equipo',
            fields=[
                ('id_grupo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('id_equipo', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='gestion_encuentro.grupo')),
            ],
            options={
                'db_table': 'grupo_equipo',
            },
        ),
    ]
