# Generated by Django 6.0.5 on 2026-05-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_encuentro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='nombre',
            new_name='grupo',
        ),
        migrations.AddField(
            model_name='grupo_equipo',
            name='derrotas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupo_equipo',
            name='empates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupo_equipo',
            name='partidos_jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupo_equipo',
            name='victorias',
            field=models.IntegerField(default=0),
        ),
    ]
