# Generated by Django 5.2.14 on 2026-05-28 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id_reglas', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_reglas', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reglas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_deporte',
            fields=[
                ('id_tipo_deporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_deporte', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_deporte',
            },
        ),
        migrations.CreateModel(
            name='Tipo_distribucion',
            fields=[
                ('id_tipo_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_distribucion',
            },
        ),
        migrations.CreateModel(
            name='Tipo_reglamento',
            fields=[
                ('id_tipo_reglamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_tipo_deporte', models.ForeignKey(db_column='id_tipo_deporte', on_delete=django.db.models.deletion.CASCADE, to='api.tipo_deporte')),
            ],
            options={
                'db_table': 'tipo_reglamento',
            },
        ),
    ]
