# Generated by Django 5.2.14 on 2026-06-01 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad_jugadores', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Premiacion',
            fields=[
                ('id_premiacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_premiacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'premiacion',
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id_integrante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
            ],
            options={
                'db_table': 'integrantes',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id_torneo', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_deporte', models.IntegerField()),
                ('nombre_torneo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ubicacion', models.TextField()),
                ('objetivo', models.TextField()),
                ('fecha_fase', models.TextField()),
                ('cantidad_equipo', models.IntegerField()),
                ('id_tipo_distribucion', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_premiacion', models.ForeignKey(db_column='id_premiacion', on_delete=django.db.models.deletion.CASCADE, to='api.premiacion')),
            ],
            options={
                'db_table': 'torneo',
            },
        ),
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id_reglamento', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_reglamento', models.IntegerField()),
                ('id_reglas', models.IntegerField()),
                ('id_tipo_deporte', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_torneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='api.torneo')),
            ],
            options={
                'db_table': 'reglamento',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.TextField()),
                ('tipo_imagen', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_torneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='api.torneo')),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='HistorialTorneos',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_torneo', models.CharField(max_length=255)),
                ('id_usuario', models.IntegerField()),
                ('deporte', models.CharField(max_length=100)),
                ('reglamento', models.CharField(max_length=100)),
                ('equipos', models.IntegerField()),
                ('id_tipo_distribucion', models.IntegerField()),
                ('distribucion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('finalizacion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_torneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='api.torneo')),
            ],
            options={
                'db_table': 'historialtorneos',
            },
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_distribucion', models.IntegerField()),
                ('confirmacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_torneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='api.torneo')),
            ],
            options={
                'db_table': 'distribucion',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_encuentro', models.IntegerField()),
                ('partido_jugado', models.IntegerField()),
                ('partido_ganado', models.IntegerField()),
                ('partido_empatado', models.IntegerField()),
                ('partido_derrota', models.IntegerField()),
                ('puntos_partidos', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
                ('id_torneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='api.torneo')),
            ],
            options={
                'db_table': 'clasificacion',
            },
        ),
    ]
